services:
  - type: web
    name: crispy-octo-spoon
    runtime: node
    buildCommand: cd react-app && npm install && npm run build && cd .. && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
